### ISSUE TITLE
iclr 2019 update 

### ISSUE THREAD

**Issue by Randl** [Chillee/OpenReviewExplorer#2]
Hi, are you going to update for ICLR 2019?

**Comment by wookayin** [comment]
e.g. 9db48ff8f24394788f17a2b40e7269dafca3c757 
~(But it shows only 200 submissions. He's working on this so wait a bit more :) )~

**Comment by Chillee** [comment]
@wookayin @Randl I initially added the page limit because of performance reasons, but thinking back on it, it was definitely a bad idea to not have that option.

I noticed a couple people were forking the project to mess with page limits, so I took the solution @wookayin had and added a button at the bottom of the screen that says "show all".

**Comment by Chillee** [comment]
Other than that, I've updated for ICLR2019 and also resolved the page limit issue, so I'm going to close this issue.

**Comment by wookayin** [comment]
This is so great, thank you!
